env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parser: '@babel/eslint-parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: {}
